apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    daemon off;
    user   nginx;
    worker_processes  1;

    # error_log  /var/log/nginx/error.log warn;
    error_log /dev/stdout info;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        # access_log  /var/log/nginx/access.log  main;
        access_log /dev/stdout main;

        keepalive_timeout  5 5;
        tcp_nodelay        on;
        gzip               on;

        server_names_hash_bucket_size  64;

        server {
          listen 80 default_server;
          server_name _;

          # restrict to GET requests
          if ($request_method !~ ^(GET)$ ) {
            return 444;
          }

          location / {
            root /usr/local/src;
            index index.html index.htm;
          }
        }

    }
